### ISSUE TITLE
Galaxy support

### ISSUE THREAD

**Issue by briandoconnor** [ga4gh/tool-registry-service-schemas#79]
Are we going for this before June and 2.0?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TRS-16)
┆containerName: GA4GH tool-registry-service
┆Epic: Galaxy workflow support in Dockstore
┆Issue Number: TRS-16

**Comment by denis-yuen** [comment]
I doubt it. 
We don't have a lot of experience with Galaxy on the Dockstore team yet. We're hoping to get this experience but June seems aggressive.

**Comment by coverbeck** [comment]
1. Dockstore team is working on Galaxy support, so I think we should target this for 2.1. It already has that milestone, but just reemphasizing.
2. To be clear, this issue is for adding something like a `GALAXY` enum to the DescriptorType, right? The issue title is slightly confusing to me, as Galaxy workflows, at least the new version, are written in YAML, not XML.

**Comment by denis-yuen** [comment]
> 2. To be clear, this issue is for adding something like a `GALAXY` enum to the DescriptorType, right? The issue title is slightly confusing to me, as Galaxy workflows, at least the new version, are written in YAML, not XML.

It turns out that the plugin that is in progress would work for both, for TRS I think we have to decide whether Galaxy XML+YML counts as 1 or 2 languages
